site_name: Pronto User Documentation
site_url: https://researchit.las.iastate.edu/guides/pronto/
site_description: Documentation for the pronto cluster.
site_author: ResearchIT

repo_url: https://github.com/researchit/pronto-user-docs
edit_uri: ""
extra_css:
    - css/isu.css
    - css/codehilite.css
plugins:
    - search
    - macros
markdown_extensions:
    - toc:
        permalink: true
    - codehilite:
        guess_lang: false
theme:
    name: readthedocs
    locale: en
    analytics: {gtag: ''}
    highlightjs: false
    custom_dir: custom_theme
nav:
    - Pronto Job Manager: index.md
    - Getting Started: getting_started.md
    - Job Scheduler Basics: slurm_basics.md
    - Software Modules: spack_modules.md
    - Hardware: hardware.md
    - Picking the Best Resource For Your Job: picking_the_best_resource.md
    - Popular Uses:
        - Machine Learning / GPU:
            # first menu item is used as the link for the 'Interactive Computing' heading
            # implemented in custom_theme/nav.html
            - machine_learning/index.md
            - Pre-installed Software: machine_learning/preinstalled_software.md
            - Interactive Session: machine_learning/interactive_session.md
            - Submit Job: machine_learning/submit_job.md
            - Available GPU Types: machine_learning/gpu_types.md
            - Install Additional Python Packages: machine_learning/install_python_packages.md
            - Upgrade Existing Python Packages: machine_learning/upgrade_python_packages.md
            - Create an Empty Virtual Environment: machine_learning/create_empty_virtualenv.md
            - Common Issues: machine_learning/common_issues.md
        - Interactive Computing:
            # first menu item is used as the link for the 'Interactive Computing' heading
            # implemented in custom_theme/nav.html
            - interactive_computing/index.md
            - tmux: interactive_computing/tmux.md
            - screen: interactive_computing/screen.md
            - X Forwarding for Mac and Windows: interactive_computing/x_forwarding.md
            - SSH port forwarding: interactive_computing/ssh_port_forwarding.md
        - Python: python.md
        - R: r.md
        - Conda: conda.md
    - File Transfers:
        - Overview: file_transfers/index.md
        - Move Your Files Faster: file_transfers/move_your_files_faster.md
        - Transfer Methods:
            # first menu item is used as the link for the 'Transfer Methods' heading
            # implemented in custom_theme/nav.html
            - file_transfers/transfer_methods.md
            - Globus: file_transfers/globus.md
            - Box: file_transfers/rclone.md
            - scp: file_transfers/scp.md
            - rsync: file_transfers/rsync.md
            - robocopy: file_transfers/robocopy.md
    - Open OnDemand:
        - Overview: ondemand/index.md
        - Interactive Desktop: ondemand/interactive_desktop.md
        - JupyterLab: ondemand/jupyterlab.md
        - Job Composer: ondemand/job_composer.md
    - Troubleshooting:
        - Common Issues: troubleshooting/common_issues.md
        - Reporting Issues: troubleshooting/reporting_issues.md